# Generated by cpp11: do not edit by hand

client_version <- function() {
  .Call(`_RPostgres_client_version`)
}

connection_create <- function(keys, values, check_interrupts) {
  .Call(`_RPostgres_connection_create`, keys, values, check_interrupts)
}

connection_valid <- function(con_) {
  .Call(`_RPostgres_connection_valid`, con_)
}

connection_release <- function(con_) {
  invisible(.Call(`_RPostgres_connection_release`, con_))
}

connection_info <- function(con) {
  .Call(`_RPostgres_connection_info`, con)
}

connection_quote_string <- function(con, xs) {
  .Call(`_RPostgres_connection_quote_string`, con, xs)
}

connection_quote_identifier <- function(con, xs) {
  .Call(`_RPostgres_connection_quote_identifier`, con, xs)
}

connection_is_transacting <- function(con) {
  .Call(`_RPostgres_connection_is_transacting`, con)
}

connection_set_transacting <- function(con, transacting) {
  invisible(.Call(`_RPostgres_connection_set_transacting`, con, transacting))
}

connection_import_lo_from_file <- function(con, filename, oid) {
  .Call(`_RPostgres_connection_import_lo_from_file`, con, filename, oid)
}

connection_copy_data <- function(con, sql, df) {
  invisible(.Call(`_RPostgres_connection_copy_data`, con, sql, df))
}

connection_wait_for_notify <- function(con, timeout_secs) {
  .Call(`_RPostgres_connection_wait_for_notify`, con, timeout_secs)
}

connection_get_temp_schema <- function(con) {
  .Call(`_RPostgres_connection_get_temp_schema`, con)
}

connection_set_temp_schema <- function(con, temp_schema) {
  invisible(.Call(`_RPostgres_connection_set_temp_schema`, con, temp_schema))
}

encode_vector <- function(x) {
  .Call(`_RPostgres_encode_vector`, x)
}

encode_data_frame <- function(x) {
  .Call(`_RPostgres_encode_data_frame`, x)
}

encrypt_password <- function(password, user) {
  .Call(`_RPostgres_encrypt_password`, password, user)
}

init_logging <- function(log_level) {
  invisible(.Call(`_RPostgres_init_logging`, log_level))
}

result_create <- function(con, sql, immediate) {
  .Call(`_RPostgres_result_create`, con, sql, immediate)
}

result_release <- function(res) {
  invisible(.Call(`_RPostgres_result_release`, res))
}

result_valid <- function(res_) {
  .Call(`_RPostgres_result_valid`, res_)
}

result_fetch <- function(res, n) {
  .Call(`_RPostgres_result_fetch`, res, n)
}

result_bind <- function(res, params) {
  invisible(.Call(`_RPostgres_result_bind`, res, params))
}

result_has_completed <- function(res) {
  .Call(`_RPostgres_result_has_completed`, res)
}

result_rows_fetched <- function(res) {
  .Call(`_RPostgres_result_rows_fetched`, res)
}

result_rows_affected <- function(res) {
  .Call(`_RPostgres_result_rows_affected`, res)
}

result_column_info <- function(res) {
  .Call(`_RPostgres_result_column_info`, res)
}
