# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connect <- function(keys, values) {
    .Call('rpq_connect', PACKAGE = 'rpq', keys, values)
}

con_info <- function(con) {
    .Call('rpq_con_info', PACKAGE = 'rpq', con)
}

postgres_disconnect <- function(con) {
    invisible(.Call('rpq_postgres_disconnect', PACKAGE = 'rpq', con))
}

escape_string <- function(con, xs) {
    .Call('rpq_escape_string', PACKAGE = 'rpq', con, xs)
}

escape_identifier <- function(con, xs) {
    .Call('rpq_escape_identifier', PACKAGE = 'rpq', con, xs)
}

encrypt_password <- function(password, user) {
    .Call('rpq_encrypt_password', PACKAGE = 'rpq', password, user)
}

rpostgres_send_query <- function(con, sql) {
    .Call('rpq_rpostgres_send_query', PACKAGE = 'rpq', con, sql)
}

postgres_fetch <- function(rs, n) {
    .Call('rpq_postgres_fetch', PACKAGE = 'rpq', rs, n)
}

postgresql_bind_params <- function(rs, params) {
    invisible(.Call('rpq_postgresql_bind_params', PACKAGE = 'rpq', rs, params))
}

rows_affected <- function(rs) {
    .Call('rpq_rows_affected', PACKAGE = 'rpq', rs)
}

is_complete <- function(rs) {
    .Call('rpq_is_complete', PACKAGE = 'rpq', rs)
}

clear_result <- function(rs) {
    invisible(.Call('rpq_clear_result', PACKAGE = 'rpq', rs))
}

postgres_result_valid <- function(rs) {
    .Call('rpq_postgres_result_valid', PACKAGE = 'rpq', rs)
}

postgres_row_count <- function(rs) {
    .Call('rpq_postgres_row_count', PACKAGE = 'rpq', rs)
}

postgres_column_info <- function(rs) {
    .Call('rpq_postgres_column_info', PACKAGE = 'rpq', rs)
}

