name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    # Must happen after installing system dependencies,
    # https://github.com/ankane/setup-mariadb/issues/2
    - uses: ankane/setup-postgres@v1
      with:
        postgres-version: ${{ matrix.pg-version || 14 }}

    - name: Create database
      if: runner.os != 'Windows'
      run: |
        createdb ${USER}
      shell: bash

    - name: Create database
      if: runner.os == 'Windows'
      run: |
        createdb ${USERNAME}
      shell: bash

    # Must happen after R is installed...
    - name: Define R CMD check error condition
      # Allow NOTEs on R 4.5 due to SET_TRUELENGTH, SET_GROWABLE_BIT and SETLENGTH from cpp11
      run: |
        if (getRversion() >= "4.5" && getRversion() < "4.6") {
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}
